"""Build-time-only adaptation of the shared converter to the Windows 7 CLR.

Generated C# is compiled directly against .NET 2.0/3.5, never modern .NET.
No Python is shipped or needed by users. Keep algorithm changes in ../Core.
"""
from pathlib import Path
import re

root = Path(__file__).resolve().parent
(root / 'Core').mkdir(exist_ok=True)
prefix = '''using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using Path = HaloSetup.LegacyPath;
using File = HaloSetup.LegacyFile;
using Directory = HaloSetup.LegacyDirectory;
using Convert = HaloSetup.LegacyConvert;
using Environment = HaloSetup.LegacyEnvironment;
'''

def record(m):
    access, name, args, end = m.groups()
    # Commas within Dictionary<> are not parameter separators.
    parts = re.split(r',\s*(?![^<]*>)', args)
    fields = [p.strip().split(' = ')[0].rsplit(' ', 1) for p in parts]
    props = '\n'.join('public '+t+' '+n+' { get; set; }' for t,n in fields)
    ctor = 'public '+name+'('+args+') { '+''.join('this.'+n+'='+n+';' for t,n in fields)+' }'
    default = '' if any('=' in p for p in parts) else 'public '+name+'() {}'
    return access+' sealed class '+name+' { '+props+ctor+default+('}' if end==';' else '')

for src in (root.parent/'Core').glob('*.cs'):
    s = src.read_text(encoding='utf-8-sig')
    s = s.replace('using System.Buffers.Binary;', '').replace('using System.Text.Json;', '')
    s = re.sub(r'(public|internal) sealed record (\w+)\((.*?)\)\s*(;|\{)', record, s, flags=re.S)
    s = s.replace('Dictionary<uint, string> Roots', 'Dictionary<string, string> Roots').replace('schemas.Roots.TryGetValue(group,', 'schemas.Roots.TryGetValue(group.ToString(System.Globalization.CultureInfo.InvariantCulture),')
    s = s.replace('SHA256.HashData(data)', 'LegacyHash(data)')
    s = s.replace('public static string Hash(byte[] data)', 'static byte[] LegacyHash(byte[] data) { using (var hash = new SHA256Managed()) return hash.ComputeHash(data); }\n    public static string Hash(byte[] data)')
    s = re.sub(r'"([^"\n]*)"u8', r'System.Text.Encoding.ASCII.GetBytes("\1")', s)
    s = s.replace('OperatingSystem.IsWindows()', 'true').replace('char.IsAsciiLetter(destination[0])', "((destination[0] >= 'A' && destination[0] <= 'Z') || (destination[0] >= 'a' && destination[0] <= 'z'))")
    s = s.replace('string.IsNullOrWhiteSpace(extra)', '(extra == null || extra.Trim().Length == 0)')
    s = s.replace('Encoding.Latin1', 'Encoding.GetEncoding(28591)')
    s = s.replace('n[..^6]', 'n.Substring(0, n.Length - 6)').replace('p.Key[prefix.Length..]', 'p.Key.Substring(prefix.Length)')
    s = s.replace(".Contains('/')", ".Contains(\"/\")")
    s = s.replace('HashSet<(uint, uint)>', 'HashSet<string>').replace('tables.Add((sector, size))', 'tables.Add(sector.ToString()+":"+size.ToString())')
    s = s.replace('HashSet<(string, int)>', 'HashSet<string>').replace('var key = (name, offset);', 'var key = name + ":" + offset.ToString();')
    s = s.replace('foreach (var (start, type, stride) in new[] { (176, 1u, 32L), (196, 3u, 8L) })', 'foreach (int start in new[] { 176, 196 })')
    s = s.replace('uint count = U32(offset + start + 4);', 'uint type = start == 176 ? 1u : 3u; long stride = start == 176 ? 32L : 8L;\n                        uint count = U32(offset + start + 4);')
    s = s.replace('public override int Read(byte[] b, int o, int n) => Read(b.AsSpan(o, n));\n    public override int Read(Span<byte> b)\n    {\n        int n = file.Read(b[..(int)Math.Min(b.Length, length - position)]);', 'public override int Read(byte[] b, int o, int count)\n    {\n        if (count == 0) return 0;\n        int n = file.Read(b, o, (int)Math.Min(count, length - position));')
    s = s.replace('new ZLibStream(source, CompressionMode.Decompress, true)', 'LegacyCompression.OpenZlib(source)')
    s = s.replace('static uint Crc(byte[] data)', 'static uint Crc(byte[] data)')
    (root/'Core'/src.name).write_text('// Generated by adapt-core.py; edit ../Core or the adapter.\n'+prefix+s, encoding='utf-8')

